const userDataInputs = [
  { option: 'email', 
    label: 'Email',
    placeholder: 'E-mail of the employee',
    readonly: true,
  },
  { option: 'ad_user',
    label: 'AD account',
    placeholder: 'Active Directory account',
    readonly: true,
  },
  { option: 'company_name',
    label: 'Company',
    placeholder: 'Сompany the employee works',
    readonly: true,
  },
  { option: 'branch_name',
    label: 'Division',
    placeholder: 'Division of the company',
    readonly: true,
  },
  { option: 'div_name',
    label: 'Department',
    placeholder: 'Department the employee works',
    readonly: true,
  },
  { option: 'position_name',
    label: 'Position',
    placeholder: 'Employee\'s position',
    readonly: true,
  },
  { option: 'location',
    label: 'Location',
    placeholder: 'Office address',
    readonly: true,
  },
  { option: 'phone',
    label: 'Phone',
    placeholder: 'Сontact number',
    readonly: false,
  },
  { option: 'sap_branch_name',
    label: 'SAP branch',
    placeholder: 'Account in SAP system',
    readonly: true,
  },
];

export default userDataInputs;